version: "3"

services:
  api:
    image: node:10.5.0
    command: npm run start-dev
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/_ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_DATABASE=db
  db:
    image: postgres:10.3
    ports:
      - 5432:5432
    command: postgres -D /run/pgsql-10.3-data -F -c logging_collector=on
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      PGDATA: /run/pgsql-10.3-data
      LOGGING_COLLECTOR: 'on'
